### ISSUE TITLE
Configurable page size

### ISSUE THREAD

**Issue by pellenys** [atrenton/MyJournal.Notebook#1]
Would it be possible to consider a configuration option for the default page size for new pages? It appears to currently create them as Letter sized pages, whereas that means that eventually enough text will over-spill the coloured background. I change the page size to Auto and all works well, but it would be good for that to be an option as a default.

P.S. Brilliant add-in - thank you!

**Comment by atrenton** [comment]
This is a known OneNote issue. I have posted feedback to OneNote for Windows UserVoice forum. All interested parties should upvote this item: [Ability to have defined horizontal margins and infinite vertical defined pages.. ](https://onenote.uservoice.com/forums/327186-onenote-for-windows/suggestions/10022610-ability-to-have-defiined-horizontal-margins-and-in)
See attached screenshot showing that OneNote page content exceeding the defined Letter page height will overflow the fixed height background page color.
![OneNote Letter Paper Size Overflow](https://user-images.githubusercontent.com/48064181/68885673-98da2f00-06e3-11ea-99c3-7213e8129658.png)

**Comment by atrenton** [comment]
Release 16.1.0 will support a user's paper size preference for the My Journal notebook. It will default to the OneNote Auto (automatic) paper size.

**Comment by pellenys** [comment]
Hi @atrenton . I've just tried the new release - it's perfect for what I needed, thank you!

**Comment by atrenton** [comment]
Hi [@pellenys](https://github.com/pellenys). So glad to hear the new release is meeting your needs. Thank you for your feedback.

Additional project documentation has been added describing this as a [known issue](https://github.com/atrenton/MyJournal.Notebook/blob/master/docs/known-issues.md).
