### ISSUE TITLE
"...is not a valid Office Add In"

### ISSUE THREAD

**Issue by ehsomma** [atrenton/MyJournal.Notebook#2]
Hey Atrenton! Excellent work, it's a piece of art, perfect code and really well documented. 
But I have a problem.  I compile the project perfectly, but when I try to add it to onenote (from Options->AddIns->COM AddIns and GO) I always get the error "'<path>' is not a valid Office Add In.".
I try a lot of others examples and always get the same error "...is not a valid Office Add In.".

If I use your installer, it installs perfectly. What you do in you installer? Or do you know what I'm doing wrong?

I have VS2017 15.3.3 and OneNote 2016 64b (desktop).

Thank you
Esteban
(a OneNote Lover)

**Comment by atrenton** [comment]
Attempting to manually Add the **MyJournal.Notebook.dll** via the File &#x2192; Options &#x2192; Add-ins &#x2192; Manage: COM Add-ins &#x2192; Go... button is not supported.

That dialog only works with classic COM servers which export two functions - `DllRegisterServer` and `DllUnregisterServer` - to handle the COM registration.

The **MyJournal.Notebook.dll** manages its registration via the `RegisterComponent` and `UnregisterComponent` methods in the 
[MyJournal.Notebook.Connect](https://github.com/atrenton/MyJournal.Notebook/blob/master/src/add-in/Connect.cs) COM visible class.

The DLL assembly is registered for COM interop using the [RegAsm.exe assembly registration tool](https://docs.microsoft.com/en-us/previous-versions/dotnet/netframework-4.0/tzat5yw6(v=vs.100)).

This is done for you automatically within **Visual Studio** when you build the solution, so there is no need to manually add it.

The **MyJournal.Notebook.Setup** program also invokes RegAsm to create the registry entries for the Add-in during the installation.

If you need to manually deploy your own DLL on another PC, take a look at the [Register-MyJournal-Notebook.ps1](https://github.com/atrenton/MyJournal.Notebook/blob/master/docs/troubleshooting/Register-MyJournal-Notebook.ps1) PowerShell Script.

**Comment by ehsomma** [comment]
Thank you atrenton!
