### ISSUE TITLE
Feature request: configure the notebook used

### ISSUE THREAD

**Issue by tridian-tn** [atrenton/MyJournal.Notebook#3]
I use your add-in regularly but only on one PC - it would be really helpful if the add-in could be optionally configured to use a different notebook (such as one on OneDrive) so that I could choose one that's synced. It doesn't even matter if there's no UI to configure it - a manually configured setting somewhere would be great.

Either way, thanks for developing this add-in. It's really good.

**Comment by atrenton** [comment]
A feasibility study has been completed for this feature request. A new beta release should be available for testing sometime in Q1 2021.

The user will be able to select a OneDrive account from a dropdown list to store their 'My Journal' notebook in the cloud or choose to keep the notebook on local storage (default behavior).

This may create a dependency on the Microsoft [OneDrive for Windows](https://www.microsoft.com/en-us/microsoft-365/onedrive/download) software being installed, not sure yet.

**Comment by atrenton** [comment]
[v16.2.1-beta](https://github.com/atrenton/MyJournal.Notebook/releases/tag/v16.2.1-beta) has been published

**Comment by atrenton** [comment]
This feature request has been released from beta in [v16.3.0](https://github.com/atrenton/MyJournal.Notebook/releases/tag/v16.3.0). Comments can be posted to the Discussion conversation [here](https://github.com/atrenton/MyJournal.Notebook/discussions/5).
